## Домашнее задание. Часть 1.

- напишем свою собственную библиотеку

Вего за эту часть ДЗ можно набрать максимум **11.5 баллов**. Разбиение баллов по каждой из задач представлено непосредственно перед текстом каждой задачи.

**Дедлайн - пятница, 11.12.2020 в 23:59.**

Дедлайн жесткий, сдача после дедлайна - 0 баллов за ДЗ.

Ссылка на ноутбук в колабе: https://colab.research.google.com/drive/1LgWtESFmiNW1WlVFCHKyNl_BxAWxoL3Z?usp=sharing

# Ссылка на ДЗ в гитхабе

https://colab.research.google.com/drive/1w4UAwf1JfsoKbBk3wybLLQjrWqKo16t_?usp=sharing

Допустим мы хотим написать фнкцию, которая складывает 2 числа и сохранить ее в отдельный .py файл. Пример:

In [ ]:
%%writefile lib.py
def summ(a1, b1):
    return a1+b1

Overwriting lib.py


In [ ]:
from lib import summ

In [ ]:
summ(2,6)

8

Попробуем запустить через "терминал"

In [ ]:
!python3 lib.py

Ничего не происходит. А теперь добавим `if __name__ == "__main__"` в наш код и пересохраним файл lib.py

In [ ]:
%%writefile lib.py
import sys

a1 = float( sys.argv[1] ) # Считываем аргументы прямо из терминала
b1 = float( sys.argv[2] ) # Считываем аргументы прямо из терминала

def summ(a1, b1):
    return a1+b1

if __name__ == "__main__":
    print(summ(a1, b1))


Overwriting lib.py


In [ ]:
!python3 lib.py 2 4

6.0


# **Задание 1**

Реализуйте следующие функции и сохраните их в библиотеку **my_math_lib.py** (пока без использования конструкции `if __name__ == "__main__"`)

**1 point** 
1. **def deg_to_rad()**. Напишите программу на Python для преобразования градусов в радианы.  *(Note: Радиан - это стандартная единица измерения угла, используемая во многих областях математики. Измерение угла в радианах численно равно длине соответствующей дуги единичного круга; один радиан чуть меньше 57,3 градуса)* **1 point**

**1 point** 
2. **def rad_to_def()**. Напишите программу Python для преобразования радианов в градусы.

**1.5 point** 
3. **def discriminant()**. Напишите программу на Python для вычисления значения дискриминанта (вспоминаем квадратные уравнения). Входные данные три числа: x, y, z (учтите что корни могут быть комлЕксными!)

**1.5 point** 
4. **def power_base_sum()**. Напишите программу на Python, чтобы вычислить сумму всех цифр основания в указанной степени.

Пример: power_base_sum(2, 100)

Выход: 115



**2 point** 
5. **def magic_square()**. Напишите программу на Python для вычисления [магического квадрата](https://ru.wikipedia.org/wiki/Магический_квадрат)

Note:

Магический, или волшебный квадрат — это квадратная таблица , заполненная числами таким образом, что сумма чисел в каждой строке, каждом столбце и на обеих диагоналях одинакова. Сумма чисел в каждой строке, столбце и на диагоналях, называется магической константой, M.

**1 point** 
6. **def mult_list()**. Напишите функцию Python для умножения всех чисел в массиве list(), (размер листа на входе произвольный)

**1 point** 
7. **def create_list()**. Напишите функцию Python для создания и вывода списка (при помощи print()), в котором значения представляют собой квадрат чисел от 1 до 30 (оба включительно).

In [1]:
#TODO
%%writefile my_math_lib.py
import sys
import math
from random import randint
import numpy as np

# Напишите программу на Python для преобразования градусов в радианы. (Note: Радиан - это стандартная единица измерения угла, используемая во многих областях математики. 
# Измерение угла в радианах численно равно длине соответствующей дуги единичного круга; один радиан чуть меньше 57,3 градуса) 

def deg_to_rad(rad):
    return 180*rad/math.pi

 # Считываем аргументы прямо из терминала

#. Напишите программу Python для преобразования радианов в градусы.
def rad_to_def(deg):
    return math.pi * deg /180  

# Напишите программу на Python для вычисления значения дискриминанта (вспоминаем квадратные уравнения). 
# Входные данные три числа: x, y, z (учтите что корни могут быть комлЕксными!)

def discriminant(a, b, c):
    D = b**2 - 4 * a * c
    x = (- b) /(2*a)
    dx = ((abs(D))**0.5)/(2*a) # чтоб красивый вывод был, если корень из дискриминанта не комплексное число
    if D < 0:
        dx = (complex(D**0.5))/(2*a)          
    return x - dx, x + dx

# Напишите программу на Python, чтобы вычислить сумму всех цифр основания в указанной степени.
# Пример: power_base_sum(2, 100)
# Выход: 115
def power_base_sum(x, y):
    power = str(x**y)
    summ = 0
    for i in power:
        summ += int(i)
    return summ

# Напишите программу на Python для вычисления магического квадрата
# Note:
# Магический, или волшебный квадрат — это квадратная таблица , заполненная числами таким образом, 
# что сумма чисел в каждой строке, каждом столбце и на обеих диагоналях одинакова. 
# Сумма чисел в каждой строке, столбце и на диагоналях, называется магической константой, M.

def magic_square(n):
    #if n > 4 and n % 2 == 1:
    square = np.array([0 for i in np.arange(n**2)])
    square = square.reshape(n,n)
    for i in range(1,n + 1):
        for j in range(1,n + 1):
          square[i-1][j-1] = int(1 + ((i + j - 1 + (n-1)/2)%n)* n + ((i + 2*j + 2)%n))
    return square

# Напишите функцию Python для умножения всех чисел в массиве list(), (размер листа на входе произвольный)
def mult_list(list):
    p = 1
    for i in list:
      p *= i
    return p

# Напишите функцию Python для создания и вывода списка (при помощи print()), 
# в котором значения представляют собой квадрат чисел от 1 до 30 (оба включительно).
def create_list():
     print([i**2 for i in range(1,31)])

if __name__ == "__main__":
    rad = float( sys.argv[1] )
    print(deg_to_rad(rad))
    deg = float( sys.argv[2] )
    print(rad_to_def(deg))
    x = float( sys.argv[3] )
    y = float( sys.argv[4] )
    z = float( sys.argv[5] )
    print(discriminant(x, y, z))
    n = int( sys.argv[6] )
    list = list(range(1,randint(2,n)))
    print(mult_list(list))
    n = int( sys.argv[7] )
    print(magic_square(n))


Writing my_math_lib.py


In [2]:
from my_math_lib import *

In [4]:
deg = deg_to_rad(3)
print(deg)
print(rad_to_def(deg))
print(discriminant(1, 1, 1))
list1 = [i for i in range(1, randint(2,10))]
print(mult_list(list1)) 
create_list()
print(power_base_sum(2, 100))
magic_square(4)

171.88733853924697
3.0
((-0.5-0.8660254037844386j), (-0.49999999999999994+0.8660254037844386j))
40320
[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900]
115


array([[12, 18,  4, 10],
       [17,  3,  9, 11],
       [ 6,  8, 14, 16],
       [ 7, 13, 15,  5]])

# **Задание 2**
Импортируйте все методы из модуля my_math_lib.

 **0.25 point** 
 - при помощи функции **def discriminant()** посчитайте дискриминант следующего уравнения: 
 $x^{2}+3 x+4=0$

**0.25 point** 
 - постройте магический квадрат размера 5х5

In [ ]:
from my_math_lib import * #TODO

In [ ]:
print(discriminant(1,3,4))
magic_square(5)


((-1.5-1.3228756555322954j), (-1.5+1.3228756555322954j))


array([[16, 23,  5,  7, 14],
       [22,  4,  6, 13, 20],
       [ 3, 10, 12, 19, 21],
       [ 9, 11, 18, 25,  2],
       [15, 17, 24,  1,  8]])

# **Задание 3**

**2 point**
* Добавьте в вашу библиотеку конструкцию `if __name__ == "__main__"`, которая должна принимать одну из вышеперечисленных функций. 
* Важно! аргументы, подаваемые в функцию, должны подаваться напряму через терминал (как в примере)! Используйте для этого библиотеку `sys`

In [ ]:
#TODO
%%writefile my_math_lib.py
import sys
import math
from random import randint
import numpy as np

# Напишите программу на Python для преобразования градусов в радианы. (Note: Радиан - это стандартная единица измерения угла, используемая во многих областях математики. 
# Измерение угла в радианах численно равно длине соответствующей дуги единичного круга; один радиан чуть меньше 57,3 градуса) 

def deg_to_rad(rad):
    return 180*rad/math.pi

 # Считываем аргументы прямо из терминала

#. Напишите программу Python для преобразования радианов в градусы.
def rad_to_def(deg):
    return math.pi * deg /180  

# Напишите программу на Python для вычисления значения дискриминанта (вспоминаем квадратные уравнения). 
# Входные данные три числа: x, y, z (учтите что корни могут быть комлЕксными!)

def discriminant(a, b, c):
    D = b**2 - 4 * a * c
    x = (- b) /(2*a)
    dx = ((abs(D))**0.5)/(2*a) # чтоб красивый вывод был, если корень из дискриминанта не комплексное число
    if D < 0:
        dx = (complex(D**0.5))/(2*a)          
    return x - dx, x + dx

# Напишите программу на Python, чтобы вычислить сумму всех цифр основания в указанной степени.
# Пример: power_base_sum(2, 100)
# Выход: 115
def power_base_sum(x, y):
    power = str(x**y)
    summ = 0
    for i in power:
        summ += int(i)
    return summ

# Напишите программу на Python для вычисления магического квадрата
# Note:
# Магический, или волшебный квадрат — это квадратная таблица , заполненная числами таким образом, 
# что сумма чисел в каждой строке, каждом столбце и на обеих диагоналях одинакова. 
# Сумма чисел в каждой строке, столбце и на диагоналях, называется магической константой, M.

def magic_square(n):
    if n > 4 and n % 2 == 1:
        square = np.array([0 for i in np.arange(n**2)])
        square = square.reshape(n,n)
        for i in range(1,n + 1):
            for j in range(1,n + 1):
              square[i-1][j-1] = int(1 + ((i + j - 1 + (n-1)/2)%n)* n + ((i + 2*j + 2)%n))
        return square

# Напишите функцию Python для умножения всех чисел в массиве list(), (размер листа на входе произвольный)
def mult_list(list):
    p = 1
    for i in list:
      p *= i
    return p

# Напишите функцию Python для создания и вывода списка (при помощи print()), 
# в котором значения представляют собой квадрат чисел от 1 до 30 (оба включительно).
def create_list():
     print([i**2 for i in range(1,31)])

if __name__ == "__main__":
    rad = float( sys.argv[1] )
    print(deg_to_rad(rad))
    deg = float( sys.argv[2] )
    print(rad_to_def(deg))
    x = float( sys.argv[3] )
    y = float( sys.argv[4] )
    z = float( sys.argv[5] )
    print(discriminant(x, y, z))
    n = int( sys.argv[6] )
    list = list(range(1,randint(2,n)))
    print(mult_list(list))
    n = int( sys.argv[7] )
    print(magic_square(n))

Overwriting my_math_lib.py


In [ ]:
# Пример вызова функции - Вы можете вызвать любую другую
!python3 my_math_lib.py 3 171.88733853924697 1 2 1 100 7 # Например если в __main__ вы указали def discriminant()

171.88733853924697
3.0
(-1.0, -1.0)
61234458376886086861524070385274672740778091784697328983823014963978384987221689274204160000000000000000
[[34 36 45  5 14 16 25]
 [42 44  4 13 15 24 33]
 [43  3 12 21 23 32 41]
 [ 2 11 20 22 31 40 49]
 [10 19 28 30 39 48  1]
 [18 27 29 38 47  7  9]
 [26 35 37 46  6  8 17]]
