https://colab.research.google.com/drive/1E4iwTNy2uERueLWqzrVJD-KgBu8mnemA?usp=sharing

__2.__
Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$


сумма 

$A + B =\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ + $\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}$ = $\begin{pmatrix}
1+4 & (-2)+(-1)\\ 
3+0 & 0+5
\end{pmatrix}$= $\begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$

Произведение

$A * B =\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ * $\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}$ = $\begin{pmatrix}
1*4 + (-2)*0 & 1*(-1)+(-2)*5\\ 
3*4+0*0 & 3*(-1)+ 0*5
\end{pmatrix}$= $\begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}$

In [10]:
import numpy as np
a = np.array([[1,-2],[3,0]])
b = np.array([[4,-1],[0,5]])
c = a + b
d = a @ b
print(c)
print(d)

[[ 5 -3]
 [ 3  5]]
[[  4 -11]
 [ 12  -3]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$3A-2B+4C$ = $3*\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$ - $2*\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$ + $4*\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}$ = $\begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix}$ - $\begin{pmatrix}
0 & 10\\ 
4 & -2
\end{pmatrix}$ + $\begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix}$ = $\begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$ 

In [11]:
import numpy as np
a = np.array([[1,7],[3,-6]])
b = np.array([[0,5],[2,-1]])
c = np.array([[2,-4],[1,1]])
d = 3*a - 2*b + 4*c 
print(d)

[[ 11  -5]
 [  9 -12]]


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

$A^{T}=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3\\ 
\end{pmatrix}$

$AA^{T} = \begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}*\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3\\ 
\end{pmatrix}
= = \begin{pmatrix}
4*4+1*1 & 5*4+(-2)* 1 & 2*4 +3*1\\ 
4*5+1*(-2) & 5*5+(-2)*(-2)& 5*2+(-2)*3\\ 
2*4+3*1 & 2*5+3*(-2)& 2*2+3*3 \\
\end{pmatrix} = \begin{pmatrix}
17 & 18 & 11\\ 
18 & 29& 4\\ 
11 & 4& 13 \\
\end{pmatrix}$
$A^{T}A = \begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3\\ 
\end{pmatrix}* \begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3 \\
\end{pmatrix} = 
\begin{pmatrix}
4*4+5*5+2*2 & 1*4+(-2)*5+3*2\\ 
1*4+ (-2)*5+3*2& 1*1+ (-2)*(-2)+3*3\\
\end{pmatrix}  = \begin{pmatrix}
45 & 0\\ 
0 & 14\\

\end{pmatrix}                                         $



In [50]:
import numpy as np
a = np.array([[4,1],[5,-2],[2,3]])
b = a.transpose()
print(b)
c = np.dot(a, b) 
d = b @ a 
print(c)
print(d)

[[ 4  5  2]
 [ 1 -2  3]]
[[17 18 11]
 [18 29  4]
 [11  4 13]]
[[45  0]
 [ 0 14]]


5*. Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [73]:
def multi_matrix(a,b): # функция для перемножения двух произвольных матриц
  if a.shape[0] == b.shape[1]:# проверка совпадения количества строк 1 матрицы с количеством столбцов 2 матрицы
    result_matrix = np.zeros(a.shape[0]*a.shape[0]).reshape(a.shape[0], a.shape[0]) # создание 0 результирующей  матрицы
    # заполнение результирующей матрицы
    for i in range(a.shape[0]):
        for j in range(b.shape[1]):
            for p in range(b.shape[0]):
                result_matrix[i][j] += a[i][p]*b[p][j]   
         
    return result_matrix
  else:
    return f'количество строк 1 матрицы = {a.shape[0]} не совпадает с количеством столбцов 2 матрицы = {b.shape[1]}'
a = np.array([[5,1],[1,1],[2,7]])# Любая матрица
b = a.transpose() # матрица для проверки, гарантировано будет перемножаться 
print(multi_matrix(a,b)) # должен быть результат 100%
print(multi_matrix(a,a)) 

[[26.  6. 17.]
 [ 6.  2.  9.]
 [17.  9. 53.]]
количество строк 1 матрицы = 3 не совпадает с количеством столбцов 2 матрицы = 2


__6.__ Вычислить определитель (используйте любой удобный для вас способ вычисления определителя: через миноры, через перестановки или другой):

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

$det = sinx * sinx - (-cosx) * cosx = sin^2x+cos^2x =1$

   б)
    
$$\begin{vmatrix}
8 & 4 & 6\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$

$det  = 8 * (5*9 - 1*0) - 4* (0*9-1*0) + 6 * (0*0-5*0) = 360$
    
   в)

$$\begin{vmatrix}
2 & 3 & 4\\ 
5 & 6 & 7\\ 
8 & 9 & 10
\end{vmatrix}.$$

$det =  2*(6*10- 7*9) - 3*(5·10 - 7·8) + 4*(5*9 - 6*8)= 0$

In [76]:
import numpy as np
import math
a = np.array([[math.sin(0),-math.cos(0)],[math.cos(0),math.sin(0)]])
print(np.linalg.det(a))
b = np.array([[8,4,6],[0,5,1],[0,0,9]])
print(np.linalg.det(b))
c = np.array([[2,3,4],[5,6,7],[8,9,10]])
print(np.linalg.det(c))

1.0
360.00000000000006
0.0


_7._ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2}) = (detA)^{2}) = 4*4 = 16$;
    
   б) $det(A^{T})=det(A) = 4$;
    
   в) $det(2A) = 2 * det(A) = 2* 4 = 8$.
   

__8.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.
Матрица называется сингулярной, или вырожденной, если ее определитель равен нулю.

Посчитаем определитель матрицы:
$$det\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}=-(-2)·(-14)·13 + 7·6·(-3) + (-3)·4·7 - (-3)·(-14)·(-3) - (-2)·6·7 - 7·4·13 = 364 - 126 - 84 + 126 + 84 - 364 = 0 $$

In [77]:
import numpy as np
import math
c = np.array([[-2,7,-3],[4,-14,6],[-3,7,13]])
print(np.linalg.det(c))

0.0


__9.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$
сумма 1 и 2 строки равны 3 строке, значит 3 строка зависимая и ее можно исключить из матрицы 
далее отнимем от 1 строки 2 строку получим матрицу,в которой ненулевых строк 2, то Rank = 2 
$\begin{pmatrix}
1 & 2 & 3\\ 
0 & 1 & 2\\ 
0 & 0 & 0
\end{pmatrix}$

б) 
$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$
все тоже самое с помощью преобразвания строк (сумма 1 и 2 равна 3) можно исключить 3 строку, тнимем от 2 строки первую  - и получим следующий вид
$\begin{pmatrix}
0 & 0 & 0 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 0 & 0\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$
 на основании этого можно сделать вывод что  Rank = 3


In [82]:
import numpy as np
a = np.array([[1,2,3],[1,1,1],[2,3,4]])
print(f'Ранг матрицы a: {np.linalg.matrix_rank(a)}')
b = np.array([[0,0,0,1],[0,0,2,2],[0,0,4,3],[2,3,5,6]])
print(f'Ранг матрицы b: {np.linalg.matrix_rank(b)}')



Ранг матрицы a: 2
Ранг матрицы b: 3
